scan-radius: 100
max-uses: 25
glow: true
messages:
  searching: "&8▸ &5&lСКАНИРОВАНИЕ &8┃ &d%time% &7сек. &8┃ &d✦✦✦"
  blocked: "&8▸ &c&lНЕЛЬЗЯ &8┃ &fСканер нельзя ставить внутри привата"
  not-found: "&8▸ &7Тишина... &8┃ &fПохоже, здесь никто не живет"
  found: "&8▸ &5&lСИГНАЛ НАЙДЕН &8┃ &dЯ нашел чей-то приват!"
item:
  name: "&5Сканер приватов"
  lore:
    - "&7Ищет приваты вокруг"
    - "&7Осталось использований: &e%uses%"
